"""
- Inserindo funcionalidades no código, através do recurso Signals e Slots, pelo qual é um
um poderoso recurso do Qt que permite a inserção de funcionalidades em aplicações gráficas.
- Signals se refere a ações de um objeto.
- Slots se refere a respostas ou reações de um objeto.
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ADRIANO\Desktop\00-Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 151)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonCopiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCopiar.setGeometry(QtCore.QRect(260, 40, 75, 23))
        self.pushButtonCopiar.setObjectName("pushButtonCopiar")
        self.pushButtonColar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonColar.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.pushButtonColar.setObjectName("pushButtonColar")
        self.lineEditInserir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInserir.setGeometry(QtCore.QRect(110, 40, 113, 20))
        self.lineEditInserir.setObjectName("lineEditInserir")
        self.lineEditColar = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditColar.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.lineEditColar.setObjectName("lineEditColar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # self.objeto.signal.connect(self.objeto.slot)
        self.pushButtonCopiar.pressed.connect(self.lineEditInserir.selectAll)
        self.pushButtonCopiar.released.connect(self.lineEditInserir.copy)
        self.pushButtonColar.clicked.connect(self.lineEditColar.paste)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonCopiar.setText(_translate("MainWindow", "Copiar"))
        self.pushButtonColar.setText(_translate("MainWindow", "Colar"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
