# Generated by Django 4.0.2 on 2022-03-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_descricao_curta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
