# Generated by Django 4.0.2 on 2022-03-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
