# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ADRIANO\Documents\GitHub\Curso-de-Python\Secao06-PyQT5-Interface-Grafica\Aula159-Adicionando-PyQT5-em-codigo-antigo\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 169)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelRetorno = QtWidgets.QLabel(self.centralwidget)
        self.labelRetorno.setGeometry(QtCore.QRect(10, 90, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(28)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setStyleSheet("color: green")
        self.labelRetorno.setText("")
        self.labelRetorno.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRetorno.setObjectName("labelRetorno")
        self.inputValidaCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCPF.setGeometry(QtCore.QRect(90, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.inputValidaCPF.setFont(font)
        self.inputValidaCPF.setObjectName("inputValidaCPF")
        self.btnValidaCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCPF.setEnabled(True)
        self.btnValidaCPF.setGeometry(QtCore.QRect(340, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btnValidaCPF.setFont(font)
        self.btnValidaCPF.setObjectName("btnValidaCPF")
        self.btnGeraCPF = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraCPF.setGeometry(QtCore.QRect(340, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnGeraCPF.setFont(font)
        self.btnGeraCPF.setObjectName("btnGeraCPF")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valida ou Gera CPF"))
        self.label.setText(_translate("MainWindow", "Gera CPF:"))
        self.label_2.setText(_translate("MainWindow", "Valida CPF:"))
        self.btnValidaCPF.setText(_translate("MainWindow", "VALIDAR"))
        self.btnGeraCPF.setText(_translate("MainWindow", "GERAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
