# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ADRIANO\Desktop\00-Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(425, 203)
        font = QtGui.QFont()
        font.setPointSize(10)
        Interface.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(160, 100, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        Interface.setCentralWidget(self.centralwidget)

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "MainWindow"))
        self.btn.setText(_translate("Interface", "Botão"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Interface = QtWidgets.QMainWindow()
#     ui = Ui_Interface()
#     ui.setupUi(Interface)
#     Interface.show()
#     sys.exit(app.exec_())
